[package]
name = "ai-integration"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
regex = "1.11.1"
reqwest = { version = "0.12.20", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
