[package]
name = "ai-integration"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures-util = "0.3.31"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
regex = "1.11.1"
reqwest = { version = "0.12.20", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
